# Generated by Django 6.0.7 on 2026-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="default_image_category_1.png",
                upload_to="categories/",
                verbose_name="Изображение",
            ),
        ),
    ]
